import { describe, expect, it } from "vitest";
import { toInk } from "../../src/export/ink.js";
import { makeLine } from "../helpers.js";

describe("toInk", () => {
  it("emits a header followed by one line per entry", () => {
    const output = toInk([makeLine("Real coin, or don't waste my time.", 1, "Marta")]);
    const lines = output.split("\n");
    expect(lines[0]).toMatch(/^\/\/ Generated by CanvasLoop/);
    expect(lines[1]).toBe("Marta: Real coin, or don't waste my time. # speaker:Marta");
  });

  it("emits plain text with no tag for a line with no speaker", () => {
    const output = toInk([makeLine("The door creaks shut.", 1)]);
    expect(output).toContain("The door creaks shut.");
    expect(output).not.toContain("# speaker:");
  });

  it("escapes a leading character that would otherwise open ink syntax", () => {
    const output = toInk([makeLine("* Not a choice, just dialogue.", 1)]);
    expect(output).toContain("\\* Not a choice, just dialogue.");
  });

  it("accepts a custom header", () => {
    const output = toInk([makeLine("Hi.", 1)], { header: "// custom" });
    expect(output.split("\n")[0]).toBe("// custom");
  });
});
