import type { DialogueLine } from "../types.js";

export interface InkExportOptions {
  header?: string;
}

const DEFAULT_HEADER = "// Generated by CanvasLoop — hand-edit only outside generated sections";

// Characters that open ink syntax at the start of a line (choices, gathers,
// diverts, knots, logic, tags, inline expressions).
const LEADING_SYNTAX = /^[*+\-~#{<>=]/;

function escapeLeadingSyntax(text: string): string {
  return LEADING_SYNTAX.test(text) ? `\\${text}` : text;
}

/**
 * Exports accepted lines as flat ink content (no knot/branch structure —
 * that's a narrative-design decision out of scope for this tool). Speaker
 * attribution is kept both in the visible text (for a human skimming the
 * file) and as an ink tag, so an engine that reads tags can pull it out
 * structurally without re-parsing the "Speaker:" convention.
 */
export function toInk(lines: DialogueLine[], options: InkExportOptions = {}): string {
  const header = options.header ?? DEFAULT_HEADER;
  const body = lines.map((line) => {
    const text = escapeLeadingSyntax(line.text);
    return line.speaker ? `${line.speaker}: ${text} # speaker:${line.speaker}` : text;
  });
  return [header, ...body, ""].join("\n");
}
