import type { DialogueLine } from "../types.js";
import { lineKey } from "./json-table.js";

function escapeStringsValue(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * Exports accepted lines in an iOS-`.strings`-style `"key" = "value";`
 * format — a plain UI-string target with no native metadata slot, so the
 * speaker (when present) is kept as a trailing comment rather than folded
 * into the value.
 */
export function toStringsTable(lines: DialogueLine[]): string {
  const body = lines.map((line) => {
    const key = lineKey(line.sourceLine);
    const value = escapeStringsValue(line.text);
    const comment = line.speaker ? ` // ${line.speaker}` : "";
    return `"${key}" = "${value}";${comment}`;
  });
  return ["// Generated by CanvasLoop", ...body, ""].join("\n");
}
